### ISSUE TITLE
Galaxy: Make hostname easier to change

### ISSUE THREAD

**Issue by anish-mudaraddi** [stfc/cloud-deployed-apps#136]
right now to change Galaxy's hostname - we need to be specify it in 3 different places
```yaml
oauth2-proxy:
  extraArgs:
    redirect-url: "https://my-galaxy.example.com/oauth2/callback" # 1

galaxy:
  ingress:
    hosts:
    - host: "my-galaxy.example.com" # 2
      paths:
        - path: "/"
    tls:
    - hosts:
        - "my-galaxy.example.com" # 3
      secretName: galaxy-tls
``` 

We should have a `global.hostname` that we can set and all of these need to be changed accordingly.
